### ISSUE TITLE
Traceback when trying to copy to stdout

### ISSUE THREAD

**Issue by matyasselmeci** [opensciencegrid/StashCache#85]
```
$ stashcp /user/dweitzel/public/blast/queries/query1 -
Traceback (most recent call last):
  File "/usr/bin/stashcp", line 496, in <module>
    main()
  File "/usr/bin/stashcp", line 488, in main
    result = doStashCpSingle(sourceFile=source, destination=destination, debug=args.debug)
  File "/usr/bin/stashcp", line 215, in doStashCpSingle
    payload['download_size']=dlSz
UnboundLocalError: local variable 'dlSz' referenced before assignment
```
I don't know if copying to stdout is a supported use case but either way, it should fail more gracefully than that.

**Comment by djw8605** [comment]
Ah, no, copying to stdout is not supported.  But did it create a file named "-" for you?  That is odd.  I'm not sure what the error should be in this case.

Looking at the code,

- The transfer would have had to been a success
- The resulting file didn't exist (even though the transfer was a success, not sure how that works)

**Comment by matyasselmeci** [comment]
It did not create the file. It _does_ work if I pass `./-` instead of plain `-`.
